spring:
  cloud:
    gateway:
      routes:
      - id: ms-products
        uri: lb://ms-products 
        predicates:
        - Path=/api/products/**
        
        #En PREDICATES se puede especificar varias condiciones. Si descomentásemos los de abajo, sólo
        #se podría acceder a los endpoints cuando las peticiones cumpliesen los siguientes requisitos:
        #   _ Tener un Header "token" con un dígito
        #   _ Que el método sea un GET o un POST
        #   _ Que la petición tenga un queryParam llamado "color"
        
        #- Header=token, \d+
        #- Method=GET, POST
        #- Query=color
        
        filters:
        # Aquí se definen los segmentos que componen la ruta. /api/products/** tiene 2: api, products
        # Filtro necesario para activar CircuitBreaker
        - name: CircuitBreaker
          args:
            name: products
            statusCodes: 500
        - StripPrefix=2
        - name: AddMessageAndCookie
          args:
            message: Mensaje personalizado para MS-PRODUCTS
            cookieName: GALLETA-PRODUCTS
            cookieValue: GALLETA-PRODUCTS-VALUE
        
      - id: ms-items
        uri: lb://ms-items 
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2
        
        # VER DIFERENCIA CON LA DECLARACIÓN DEL FILTRO EN MS-PRODUCTS. SON DOS FORMAS DISTINTAS DE HACER LO MISMO
        # REQUIERE @Override shortcutFieldOrder()
        - AddMessageAndCookie=Mensaje personalizado para MS-ITEMS, GALLETA-ITEMS, GALLETA-ITEMS-VALUE
        
        # FILTROS POR DEFECTO DE SPRINGCLOUD GATEWAY QUE SE ENVIAN EN EL REQUEST
        - AddRequestHeader=sc-filter-add-rq-header, 123456
        - AddRequestParameter=nombre, alex
        
        # FILTROS POR DEFECTO DE SPRINGCLOUD GATEWAY QUE SE ENVIAN EN LA RESPONSE
        - AddResponseHeader=sc-filter-add-rs-header, 123456
        #- SetResponseHeader=Content-Type, text/plain
        
#RESILIENCE4J CONFIG
resilience4j:

  #CIRCUITBREAKER CONFIG AND INSTANCES
  circuitbreaker:
    configs:
      products:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 1s
    instances:
      products:
        base-config: products
        
  #TIMELIMITER CONFIG AND INSTANCES
  timelimiter:
    configs:
      products:
        timeout-duration: 3s
    instances:
      products:
        base-config: products