spring:
  cloud:
    gateway:
      routes:
      - id: ms-products
        uri: lb://ms-products 
        predicates:
        - Path=/api/products/**
        filters:
        # Aquí se definen los segmentos que componen la ruta. /api/products/** tiene 2: api, products
        - StripPrefix=2
        
      - id: ms-items
        uri: lb://ms-items 
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2