INSERT INTO ACCOUNTS (OWNER_NAME, BALANCE) VALUES ('Andrés', 1000);
INSERT INTO ACCOUNTS (OWNER_NAME, BALANCE) VALUES ('John', 1000);

INSERT INTO BANKS (NAME, TOTAL_TRANSFERENCES) VALUES ('Cecabank', 0);